# Generated by Django 6.0.6 on 2026-07-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.PositiveIntegerField(help_text="Must match the app's build.gradle versionCode.", unique=True)),
                ('version_name', models.CharField(help_text='e.g. "1.0.0-beta.2".', max_length=64)),
                ('url', models.URLField(help_text='Where the user downloads the APK / release.')),
                ('notes', models.TextField(blank=True, help_text="What's-new text shown in the app.")),
                ('is_current', models.BooleanField(default=True, help_text='Advertise this build as the latest available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
