# Generated by Django 6.0.6 on 2026-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('suggestion', 'Suggestion'), ('bug', 'Bug'), ('praise', 'Praise'), ('other', 'Other')], default='suggestion', max_length=20)),
                ('message', models.TextField()),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('device', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(blank=True, default='website', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
