"""
Django settings for aptenbyte_api project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets/keys from a .env file next to manage.py.
load_dotenv(BASE_DIR / '.env')


def _env_list(name):
    return [v.strip() for v in os.environ.get(name, '').split(',') if v.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-8j1g#x=p+e=9szv-)_)tw#=mck@7&-79&*om^i55c*yielvnt3',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS') or (['*'] if DEBUG else [])

# Trust a reverse proxy's forwarded-proto header (nginx / traefik / Render / Fly terminate TLS).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production hardening — active whenever DEBUG is off. Clears the deploy-check warnings.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# CORS: only the website's browser JS needs cross-origin access (the Android app is native, no CORS).
# Set CORS_ALLOWED_ORIGINS in .env to the site origin(s), e.g. "https://aptenbyte.com".
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS
CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS']

# Scheme-qualified origins Django trusts for admin/CSRF POSTs (e.g. the host's HTTPS domain).
# Required for the admin login page once DEBUG is off, e.g. "https://aptenbyte-api.onrender.com".
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'accounts',
    'releases',
    'aiproxy',
    'waitlist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aptenbyte_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aptenbyte_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses DATABASE_URL (e.g. Neon Postgres) when set; falls back to local SQLite for dev.
if os.environ.get('DATABASE_URL'):
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            os.environ['DATABASE_URL'],
            conn_max_age=600,
            ssl_require=True,
        ),
    }
    # Neon's pooled endpoint runs PgBouncer in transaction mode, which doesn't
    # support server-side cursors — turn them off to avoid errors.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            # Override with SQLITE_PATH (e.g. a mounted volume) so data survives container restarts.
            'NAME': os.environ.get('SQLITE_PATH') or (BASE_DIR / 'db.sqlite3'),
        }
    }

# Tests always use fast in-memory SQLite, never the real (remote Neon) database.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    # Tests run over http on the test client; never force the https redirect
    # (it would turn every request into a 301) regardless of DJANGO_DEBUG.
    SECURE_SSL_REDIRECT = False


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Behind a TLS-terminating proxy (nginx/Caddy), trust its forwarded scheme.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Email (Brevo SMTP in production, console in dev) ───────────────────────────
# Set EMAIL_HOST_USER + EMAIL_HOST_PASSWORD (Brevo SMTP login + key) to send real
# email; without them, messages are printed to the console for local development.
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER
    else 'django.core.mail.backends.console.EmailBackend',
)
# The "from" address — must be a verified sender/domain in your Brevo account.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AptenByte <no-reply@aptenbyte.com>')

# ── AptenByte AI proxy keys (from .env) ────────────────────────────────────────
# The server holds the provider keys so the app can use AI without BYOK.
AI_KEYS = {
    'gemini': [
        k for k in (
            os.environ.get('GEMINI_API_KEY_1'),
            os.environ.get('GEMINI_API_KEY_2'),
        ) if k
    ],
    'openrouter': [
        k for k in (
            os.environ.get('OPENROUTER_API_KEY'),
            os.environ.get('OPENROUTER_API_KEY_2'),
        ) if k
    ],
    # NVIDIA NIM (build.nvidia.com) is OpenAI-compatible; key looks like "nvapi-…".
    # Accept _1/_2 (matches GEMINI_*) and the bare NVIDIA_API_KEY, so whichever
    # name you set on Render is picked up.
    'nvidia': [
        k for k in (
            os.environ.get('NVIDIA_API_KEY_1'),
            os.environ.get('NVIDIA_API_KEY_2'),
            os.environ.get('NVIDIA_API_KEY'),
        ) if k
    ],
}
# Google OAuth client IDs the mobile app signs in with (Android / iOS / web).
# A Google ID token is accepted only if its audience is one of these.
GOOGLE_OAUTH_CLIENT_IDS = _env_list('GOOGLE_OAUTH_CLIENT_IDS')

# Each provider tries its models in order, falling through on error/rate-limit.
# GEMINI_MODEL (singular) is still honoured as the first Gemini model.
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.0-flash')
GEMINI_MODELS = _env_list('GEMINI_MODELS') or list(dict.fromkeys([
    GEMINI_MODEL,
    'gemini-2.5-flash',
    'gemini-flash-latest',
]))
# Free OpenRouter models, verified against the live catalogue (2026-07-08).
# 'openrouter/free' is OpenRouter's own auto-router across free models — the most
# robust first choice; the rest are concrete free instruct models tried in turn
# on any 429/404. Availability shifts over time; override via OPENROUTER_MODELS.
OPENROUTER_MODELS = _env_list('OPENROUTER_MODELS') or [
    'openrouter/free',
    'openai/gpt-oss-120b:free',
    'openai/gpt-oss-20b:free',
    'meta-llama/llama-3.3-70b-instruct:free',
    'qwen/qwen3-next-80b-a3b-instruct:free',
    'nousresearch/hermes-3-llama-3.1-405b:free',
    'meta-llama/llama-3.2-3b-instruct:free',
]
# NVIDIA has no auto-router: exact model ids are required. These are free-to-use
# hosted NIM models (rate/credit limited). Overridable via NVIDIA_MODELS.
NVIDIA_MODELS = _env_list('NVIDIA_MODELS') or [
    'meta/llama-3.3-70b-instruct',
    'nvidia/llama-3.1-nemotron-70b-instruct',
    'meta/llama-3.1-70b-instruct',
]
