# Generated by Django 6.0.6 on 2026-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiproxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rewrites', models.PositiveIntegerField(default=0)),
                ('chats', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
